apiVersion: 1
datasources:
- name: InfluxDB
  orgId: 1
  type: influxdb
  typeLogoUrl: public/app/plugins/datasource/influxdb/img/influxdb_logo.svg
  access: proxy
  url: http://localhost:8086
  password: ''
  user: ''
  database: my_internet
  basicAuth: false
  isDefault: true
  jsonData:
    httpMode: GET
    keepCookies: []
  readOnly: false
  editable: true