{
 "title": "Internet",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Total usage",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "alias": "total Play24",
     "measurement": "dataUsage",
     "query": "SELECT \"download_month\" FROM \"autogen\".\"dataUsage\" WHERE (\"source\" = 'router') AND $timeFilter GROUP BY time(10s)",
     "select": [
      [
       { "params": [ "total_month" ], "type": "field" },
       { "params": [ " / (1024*1024*1024)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "play24" }
     ]
    },
    {
     "alias": "total Router",
     "measurement": "dataUsage",
     "query": "SELECT \"download_month\"  / (1024*1024*1024) +\"upload_month\"  / (1024*1024*1024) FROM \"autogen\".\"dataUsage\" WHERE (\"source\" = 'router') AND $timeFilter\n",
     "select": [
      [
       { "params": [ "download_month" ], "type": "field" },
       { "params": [ " / (1024*1024*1024)" ], "type": "math" }
      ],
      [
       { "params": [ "upload_month" ], "type": "field" },
       { "params": [ " / (1024*1024*1024)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "router" }
     ]
    }
   ]
  },
  {
   "title": "Download 24hrs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "alias": "Download",
     "measurement": "dataUsage",
     "select": [
      [
       { "params": [ "download_month" ], "type": "field" },
       { "params": [ " / (1024*1024*1024)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "router" }
     ]
    }
   ]
  },
  {
   "title": "Upload 24hrs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 11, "y": 14 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "measurement": "dataUsage",
     "select": [
      [
       { "params": [ "upload_month" ], "type": "field" },
       { "params": [ " /( 1024*1024*1024)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "router" }
     ]
    }
   ]
  },
  {
   "title": "Total Play24",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 14 },
   "targets": [
    {
     "measurement": "dataUsage",
     "select": [
      [
       { "params": [ "total_month" ], "type": "field" },
       { "params": [ " / (1024*1024*1024)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "play24" }
     ]
    }
   ]
  },
  {
   "title": "Max ping",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
   "targets": [
    {
     "measurement": "ping",
     "select": [
      [
       { "params": [ "max" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ping Avg",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 22 },
   "targets": [
    {
     "measurement": "ping",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ping > 75ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "ping",
     "select": [
      [
       { "params": [ "max" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Signal strength",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "signal",
     "select": [
      [
       { "params": [ "signal_strength" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "2G/3G/4G",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "signal",
     "select": [
      [
       { "params": [ "network_type" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}